### PR TITLE
TASK-53860: project front base and portlet creation

### PR DESCRIPTION
**Pull request by hakermi**
project front base and portlet creation

### CODE REVIEW

**Review by azayati — CHANGES_REQUESTED** [review]
@hakermi no need to add manually Processes properties files for all languages, only english one is needed, crowdin will create the others

**Comment by hakermi** [comment]
> @hakermi no need to add manually Processes properties files for all languages, only english one is needed, crowdin will create the others

Ok

**Review by mkrout — APPROVED** [review]
LGTM

**Review by azayati — APPROVED** [review]
LGTM

**Pull request merged**
